spring.application.name=question-generator
server.port=${SERVER_PORT:9000}
server.servlet.context-path=/lumi

# Postgres config
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5433/concurso_2}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASS:postgres}
